### ISSUE TITLE
Attribute validation

### ISSUE THREAD

**Issue by Hugo-Inmanta** [inmanta/web-console#5394] opened 2023-12-14 16:25 UTC
During instance creation
- manually typing a value that is not present from a dropdown e.g. `iso89999` in `inmanta_flavor`
- clicking away from the box
- clicking confirm (expecting the value to be `iso89999`)

The actual value in the instance is `iso5` (the last valid value for the field ?)

**Comment by Hugo-Inmanta** [comment] 2023-12-14 16:26
[Screencast from 14-12-2023 17:20:04.webm](https://github.com/inmanta/web-console/assets/98876549/82d9dd83-c16d-4547-8c02-bd864534cb5d)

**Comment by LukasStordeur** [comment] 2023-12-15 09:58
Those dropdowns are Selects, Arnaud made the same observation yesterday. The typing box is a filter, and if the value entered isn't present in the array of options, the Select will default back to either the last known value, or the default. These dropdowns don't allow the creation of new options, hence why it has to default to a valid option. 

This is a behavior inherent to Paternfly, but we can add user feedback like a red border if the user hasn't selected a valid value and clicks outside the input field. Maybe a search icon can improve the comprehension of a search field instead of an actual input.

**Comment by LukasStordeur** [comment] 2024-06-13 08:37
can't reproduce anymore, closing the ticket

**Closed by LukasStordeur** 2024-06-13 08:37 UTC
